title: SolCol Real Estate Test

collections:
  properties:
    layout: property
    output: true
    permalink: /:slugified_categories/:title

sass:
  sass_dir: assets/style
  style: compressed

defaults:
  - scope:
      path: ""
      type: "properties"
    values:
      layout: "property"
